spring:
  profiles:
    include: domain
  application:
    name: search-blog
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  banner:
    location: classpath:banner.txt

server:
  port: 80
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  default-produces-media-type: application/json
